# Set the base image.
FROM ubuntu:16.04 as builder

RUN apt-get update
RUN apt-get -y install curl gnupg
RUN apt-get -y install gcc g++ make
RUN apt-get -y install git
RUN apt-get -y install software-properties-common

RUN add-apt-repository ppa:deadsnakes/ppa 
RUN apt-get update

RUN curl -sL https://deb.nodesource.com/setup_16.x  | bash -
RUN apt-get -y install nodejs
RUN apt-get -y install build-essential
#RUN apt-get -y install python3.10
#RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 10
#RUN update-alternatives --query python3

# Create and define the working directory.
RUN mkdir /usr/src/service
WORKDIR /usr/src/service

# Install pnpm globally
RUN npm i -g pnpm

# Install the application's dependencies.
COPY package.json ./
COPY pnpm-lock.yaml ./

# Prepare ssh in case it is needed in the package install
RUN mkdir -p -m 0600 ~/.ssh
RUN ssh-keyscan -t rsa dev.curasystems.com >> ~/.ssh/known_hosts

RUN --mount=type=ssh --mount=type=secret,id=gitconfig,target=/root/.gitconfig --mount=type=secret,id=gitcredentials,target=/root/.gitcredentials  --mount=type=secret,id=npm,target=/root/.npmrc pnpm install --prod --frozen-lockfile
RUN rm package.json
RUN tar cf node_modules.tar *

FROM scratch as installresult
COPY --from=builder /usr/src/service/node_modules.tar .
